title: System Programming - Pemrograman Sistem
description: (V007-20190923) This is the CSF-227 System Programing course site.
      It contains links to lecture materials, exam questions, and laboratory materials.
      It is based on "Google Here, Google There, Try This, Try That, and then Ask Anybody".
      This site is managed by VauLSMorg (vlsm.org) since 2019.
disc: You are free to share, copy and redistribute the material of this site 
      in any medium or format for any purpose, even commercially. 
      Please give appropriate credit, provide a link to the page, 
      and indicate if changes were made. You may do so in any reasonable manner. 
      You should not apply legal terms or technological measures, 
      that legally restrict others from doing anything that is permited here.
author: Mr. Yoda Yoda
theme: jekyll-theme-midnight
show_downloads: false
# google_analytics: 
theme: jekyll-theme-hacker
sitemap: true
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
social:
  name: Systems Programing
  links:
    - https://https://github.com/UI-FASILKOM-OS/sysprog

# github:
#    zip_url: https://github.com/UI-FASILKOM-OS/SistemOperasi/archive/master.zip
#    tar_url: https://github.com/UI-FASILKOM-OS/SistemOperasi/archive/master.tar.gz

github: [metadata]

